### ISSUE TITLE
AADSTS81016

### ISSUE THREAD

**Issue by ghost** [nyxgeek/AzureAD_Autologon_Brute#6]
https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes

script didn't handle undocumented code response "AADSTS81016  Invalid STS request." well it did but with catchall.

XD

I would try to handle response with other than catchall else statement but idk where to start if i cant get docs for it :(. making issue to see if any advice.

**Comment by nyxgeek** [comment]
Sorry this took a min for me to get around to. Not actually 100% if this still works, but it now handles and quits. Thanks again!
